# Generated by Django 3.2.23 on 2024-09-26 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='art',
            field=models.CharField(blank=True, db_index=True, default='', max_length=50, verbose_name='Артикул'),
        ),
        migrations.AlterField(
            model_name='good',
            name='code',
            field=models.CharField(blank=True, default='', max_length=11, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='good',
            name='description',
            field=models.CharField(blank=True, default='', max_length=1024, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='good',
            name='manufacturer',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Производитель'),
        ),
    ]
