# Generated by Django 3.2.23 on 2024-09-26 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$260000$9tXHsleUEaqznvh0uHRm8x$kfdQ4xXNvpA9e0UjpBhMcNDICIBGv00+6Tfp7UIfM2c=', max_length=128, verbose_name='password'),
        ),
    ]
