# Generated by Django 3.2.23 on 2024-09-26 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$260000$dimpK640fN0TDBWgD8FuAn$dKS3aA+ZHcb+oCyAm9p/7Lw73iSMXLEbM1FlX5PBYmc=', max_length=128, verbose_name='password'),
        ),
    ]
