# Generated by Django 3.2.23 on 2024-09-26 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='qnt',
            new_name='quantity',
        ),
    ]
